export const ACTIVE_ORDER_STATUSES = [
  "WAITING_PAYMENT",
  "WAITING_PROOF",
  "WAITING_ADMIN_APPROVAL",
  "PAYMENT_APPROVED",
  "REQUESTING_NUMBER",
  "NUMBER_READY",
  "WAITING_OTP",
  "OTP_RECEIVED",
] as const;

export const CANCELLABLE_STATUSES = [
  "WAITING_PAYMENT",
  "WAITING_PROOF",
  "PAYMENT_REJECTED",
] as const;

export type OrderStatus =
  | "CREATED"
  | "WAITING_PAYMENT"
  | "WAITING_PROOF"
  | "WAITING_ADMIN_APPROVAL"
  | "PAYMENT_APPROVED"
  | "PAYMENT_REJECTED"
  | "REQUESTING_NUMBER"
  | "NUMBER_READY"
  | "WAITING_OTP"
  | "OTP_RECEIVED"
  | "COMPLETED"
  | "AUTO_COMPLETED"
  | "OTP_ATTEMPT_LIMIT_REACHED"
  | "FAILED"
  | "CANCELLED";
